version: '3.8'

services:
  app:
    image: move-audit-backend:1.0
    ports:
      - "5000:5000"
    volumes:
      - ./config/config.toml:/app/config/config.toml
      - ./deploy:/app/deploy
      - ./logs:/app/logs
      - ./tmp:/app/tmp
    environment:
      - PYTHONUNBUFFERED=1
      - PROD=true
    container_name: move-audit-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"