[database]
path = "deploy/orders.db"

[sui]
url = "https://fullnode.testnet.sui.io:443"

[cors]
origins = ["*"]
methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_headers = ["Content-Type", "Authorization"]
supports_credentials = true
max_age = 3600


[openai]
api_key = ""
model = "gpt-4o"